### ISSUE TITLE
Request for BeatLeader stats to be searchable too

### ISSUE THREAD

**Issue by L3Home** [bsq-ports/BetterSongSearchQuest#15]
Currently, there are options in the settings to restrict the search based on ScoreSaber ratings and/or by songs you've already placed in.

I am requesting that BeatLeader be added in the same way, and perhaps either be switchable directly within the search window (arrow over to one or the other, causing the hidden one's settings to not be included in the criteria and the active one be, instead) /or/ allow the user to set a personal toggle in the mod's settings for one or the other. I believe it's even possible for mods to check for which sibling mods are active and show/hide based on which one (or both) the player actually uses. But that isn't totally necessary, of course.

**Comment by FrozenAlex** [comment]
This needs to be fixed upstream, we use the same database as the PC BetterSongSearch. If we get it there then it's gonna get added here as well

**Comment by FrozenAlex** [comment]
Fixed in the latest update

**Comment by L3Home** [comment]
Not re-opening this, just wanted to THANK you for adding this! I tried it out and was thrilled with the result (chiefly, having a bunch of "new" ranked songs to play)!
