### ISSUE TITLE
missing libsongdetails.so

### ISSUE THREAD

**Issue by Quenii** [bsq-ports/BetterSongSearchQuest#26]
mod can't be load since missing libsongdetails.so
so, where to find it?
i can't find any mod name songdetails

**Comment by FrozenAlex** [comment]
It is a library, if you used questpatcher just find songdetails in libraries and turn it on

**Comment by Quenii** [comment]
I'm using BMBF 
I've check this page, didn't find such library
https://computerelite.github.io/tools/Beat_Saber/questmods.html

**Comment by FrozenAlex** [comment]
@Quenii On quest 2 and above BMBF will never work. V63 and above OS version has a funny scoped storage bug that makes it unusable. And libraries are not on the mods website, those are downloaded automatically by the mod manager. For more information, come to BSMG discord https://discord.gg/beatsabermods #quest-help channel

**Comment by Quenii** [comment]
thanks for reply
i upgraded it to 1.35 now
